messages-base-url: ${MESSAGES_BASE_URL:http://localhost:8080/messages}
logging.level.org.springframework.web.servlet.DispatcherServlet: debug
jwt:
  secret-key: ${JWT_SECRET_KEY}
timezone: UTC
server.servlet.context-path: /api/v1